# Generated by Django 4.2.1 on 2023-05-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
