# Generated by Django 4.2.1 on 2023-06-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='user_history', to='main_page.rentcar', verbose_name='История аренды'),
        ),
    ]
