# Generated by Django 4.2.1 on 2023-06-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='username',
        ),
    ]
