# Generated by Django 4.2.1 on 2023-06-06 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
        ('account', '0003_alter_user_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='main_page.detailcar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_bonus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
                'db_table': 'bonus_user',
            },
        ),
    ]
