# Generated by Django 4.2.1 on 2023-06-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bonus',
            field=models.IntegerField(default=0, unique=True, verbose_name='Бонусы'),
        ),
    ]
