# Generated by Django 4.2.1 on 2023-05-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_award', models.CharField(max_length=100, verbose_name='Наименование награды')),
                ('award_image', models.ImageField(upload_to='awards_image/', verbose_name='Фото награды')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
            },
        ),
        migrations.CreateModel(
            name='DetailCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_car', models.ImageField(upload_to='cars_detail_page/', verbose_name='Изображение машины')),
                ('image_brand', models.ImageField(upload_to='cars_brand_page/', verbose_name='Изображение марки машины')),
                ('name_car', models.CharField(max_length=100, verbose_name='Модель машины')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет машины')),
                ('year_car', models.IntegerField(verbose_name='Год выпуска машины')),
                ('engine_capacity', models.CharField(max_length=100, verbose_name='Обьем двигателя машины')),
                ('transmission', models.CharField(max_length=100, verbose_name='Коробка передач машины')),
                ('equipment', models.CharField(max_length=100, verbose_name='Комплектация')),
                ('price', models.CharField(max_length=100, verbose_name='Цена машины')),
                ('pledge', models.CharField(max_length=100, verbose_name='Залог')),
                ('image_car_first', models.ImageField(upload_to='cars_detail/', verbose_name='Изображение 1')),
                ('image_car_second', models.ImageField(blank=True, null=True, upload_to='cars_detail/', verbose_name='Изображение 2')),
                ('image_car_third', models.ImageField(blank=True, null=True, upload_to='cars_detail/', verbose_name='Изображение 3')),
                ('image_car_fourth', models.ImageField(blank=True, null=True, upload_to='cars_detail/', verbose_name='Изображение 4')),
                ('image_car_fifth', models.ImageField(blank=True, null=True, upload_to='cars_detail/', verbose_name='Изображение 5')),
                ('image_car_sixth', models.ImageField(blank=True, null=True, upload_to='cars_detail/', verbose_name='Изображение 6')),
                ('image_car_seventh', models.ImageField(blank=True, null=True, upload_to='cars_detail/', verbose_name='Изображение 7')),
            ],
            options={
                'verbose_name': 'Детальная информация о машине',
                'verbose_name_plural': 'Детальная информация о машине',
            },
        ),
        migrations.CreateModel(
            name='OurCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=100, verbose_name='Модель машины')),
                ('image_car', models.ImageField(upload_to='cars_main_page/', verbose_name='Изображение машины')),
                ('price', models.CharField(max_length=150, verbose_name='Цена машины')),
                ('year_car', models.IntegerField(verbose_name='Год машины')),
            ],
            options={
                'verbose_name': 'Наша машина',
                'verbose_name_plural': 'Наши машины',
            },
        ),
    ]
