# Generated by Django 4.2.1 on 2023-06-01 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailcar',
            name='image_car_fifth',
        ),
        migrations.RemoveField(
            model_name='detailcar',
            name='image_car_first',
        ),
        migrations.RemoveField(
            model_name='detailcar',
            name='image_car_fourth',
        ),
        migrations.RemoveField(
            model_name='detailcar',
            name='image_car_second',
        ),
        migrations.RemoveField(
            model_name='detailcar',
            name='image_car_seventh',
        ),
        migrations.RemoveField(
            model_name='detailcar',
            name='image_car_sixth',
        ),
        migrations.RemoveField(
            model_name='detailcar',
            name='image_car_third',
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars_image', verbose_name='Фото')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.detailcar', verbose_name='Автомобиль')),
            ],
        ),
    ]
