# Generated by Django 4.2.1 on 2023-06-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcar',
            name='bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Бонус машины'),
        ),
        migrations.AddConstraint(
            model_name='detailcar',
            constraint=models.UniqueConstraint(fields=('bonus',), name='unique_bonus'),
        ),
    ]
