# Generated by Django 4.2.1 on 2023-06-01 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_remove_detailcar_image_car_fifth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_page.detailcar', verbose_name='Автомобиль'),
        ),
    ]
