# Generated by Django 4.2.1 on 2023-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_aboutcompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurCar',
        ),
        migrations.AlterModelOptions(
            name='detailcar',
            options={'verbose_name': 'Наша машина, детальная информация о машине', 'verbose_name_plural': 'Наша машина, детальная информация о машине'},
        ),
        migrations.RemoveField(
            model_name='detailcar',
            name='image_brand',
        ),
        migrations.AlterField(
            model_name='detailcar',
            name='image_car',
            field=models.ImageField(upload_to='cars_main_page/', verbose_name='Изображение машины'),
        ),
        migrations.AlterField(
            model_name='detailcar',
            name='year_car',
            field=models.IntegerField(verbose_name='Год машины'),
        ),
    ]
