# Generated by Django 4.2.1 on 2023-06-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_delete_ourcar_alter_detailcar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcar',
            name='description_car',
            field=models.TextField(default=1, verbose_name='Описание машины'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailcar',
            name='image_brand',
            field=models.ImageField(default=1, upload_to='cars_brand/', verbose_name='Изображение бренда машины'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailcar',
            name='name_car_brand',
            field=models.CharField(default=1, max_length=100, verbose_name='Марка машины'),
            preserve_default=False,
        ),
    ]
