# Generated by Django 4.2.1 on 2023-06-02 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_detailcar_description_car_detailcar_image_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_page.detailcar', verbose_name='Изображение самой машины'),
        ),
    ]
