# Generated by Django 4.2.1 on 2023-06-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_carimage_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcar',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='Бонусы'),
        ),
        migrations.AddField(
            model_name='detailcar',
            name='hour',
            field=models.CharField(default=5, max_length=100, verbose_name='Время аренды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailcar',
            name='status',
            field=models.CharField(choices=[('Завершен', 'Завершен'), ('Отменен', 'Отменен'), ('Ожидание', 'Ожидание')], default=1, max_length=100, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
