# Generated by Django 4.2.1 on 2023-06-04 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0008_detailcar_bonus_detailcar_hour_detailcar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcar',
            name='bonus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Бонус машины'),
        ),
        migrations.AlterField(
            model_name='detailcar',
            name='hour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время аренды'),
        ),
    ]
