# Generated by Django 4.2.1 on 2023-06-04 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0009_alter_detailcar_bonus_alter_detailcar_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcar',
            name='bonus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_car', to=settings.AUTH_USER_MODEL, to_field='bonus', verbose_name='Бонус машины'),
        ),
    ]
