# Generated by Django 4.2.1 on 2023-06-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_alter_detailcar_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcar',
            name='bonus',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Бонус машины'),
        ),
    ]
