# Generated by Django 4.2.1 on 2023-06-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='изображение доп услуги')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование доп услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена доп услуги')),
                ('hour', models.CharField(blank=True, max_length=100, null=True, verbose_name='Время доп услуги')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
    ]
