# Generated by Django 4.2.1 on 2023-05-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='map',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='местоположение на карте'),
        ),
    ]
