# Generated by Django 4.2.1 on 2023-06-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moreinfo',
            options={'verbose_name': 'Подробнее про розыгрыш', 'verbose_name_plural': 'Подробнее про розыгрыши'},
        ),
    ]
